routes:
  - id: auth-service
    uri: https://auth-service-ucv6.onrender.com
    predicate: /auth_service/**
    auth-required: false

  - id: cuento-service
    uri: https://question-service-0pg5.onrender.com
    predicate: /cuento_service/**
    auth-required: false

  - id: question-service
    uri: https://question-service-ilm4.onrender.com
    predicate: /question_service/**
    auth-required: false
    
  - id: responder-service
    uri: https://response-service-ph8t.onrender.com
    predicate: /responder_service/**
    auth-required: false

server:
  port: 8090